package logKey

const (
	ServerTime            = "server_time"
	Type                  = "type"
	Id                    = "id"
	RefId                 = "ref_id"
	ServiceName           = "service_name"
	HostName              = "host_name"
	Token                 = "token"
	UserId                = "user_id"
	PlatformId            = "platform_id"
	AgentId               = "agent_id"
	OddsType              = "odds_type"
	OddsCheckType         = "odds_check_type"
	KickoffNotice         = "kick_off_notice"
	ScoreNotice           = "score_notice"
	RedCardNotice         = "red_card_notice"
	MarginGroup           = "margin_group"
	BetLimitRate          = "bet_limit_rate"
	Exemption             = "exemption"
	LastLoginTime         = "last_login_time"
	FinalMarginGroup      = "final_margin_group"
	FinalBetLimitRate     = "final_bet_limit_rate"
	IsRiskMember          = "is_risk_member"
	Method                = "method"
	RequestUri            = "request_uri"
	UserAgent             = "user_agent"
	ContentType           = "content_type"
	ClientIp              = "client_ip"
	RequestHeader         = "request_header"
	RequestHeaderLength   = "request_header_length"
	RequestTime           = "request_time"
	ContentLength         = "content_length"
	RequestBody           = "request_body"
	RequestBodySize       = "request_body_size"
	RequestCount          = "request_count"
	ResponseStatus        = "response_status"
	ResponseBody          = "response_body"
	ErrorType             = "error_type"
	ErrorMessage          = "error_message"
	Trace                 = "trace"
	TimeUsed              = "time_used"
	TimeUsedNano          = "time_used_nano"
	SlowHttp              = "slow_http"
	StackTrace            = "stack_trace"
	Sid                   = "sid"
	Tid                   = "tid"
	Gid                   = "gid"
	Gids                  = "gids"
	Mid                   = "mid"
	Vd                    = "vd"
	Msg                   = "msg"
	RoleId                = "role_id"
	OperatorId            = "operator_id"
	ForceUpdatePassword   = "force_update_password"
	LastAccessTime        = "last_access_time"
	Permissions           = "permissions"
	SlowProcess           = "slow_process"
	GetRawDataNowTime     = "get_raw_data_now_time"
	RequestBodyBufferTime = "request_body_buffer_time"
	NopCloserTime         = "nop_closer_time"
	CpuTotalPercent       = "cpu_total_percent"
	MemTotalPercent       = "mem_total_percent"
	NumGC                 = "num_gc"
	IncrNumGC             = "incr_num_gc"
	PauseTotalNs          = "pause_total_ns"
	IncrPauseNs           = "incr_pause_ns"
	ServerPanic           = "server_panic"

	RedisLuaScriptError = "redis_lua_script_error"
	RedisResult         = "redis_result"

	JsonUnmarshalError = "json_unmarshal_error"
	JsonMarshalError   = "json_marshal_error"

	KafkaGroupId   = "kafka_group_id"
	KafkaTopicName = "kafka_topic_name"
	KafkaOffset    = "kafka_offset"
	KafkaPartition = "kafka_partition"
	KafkaLag       = "kafka_lag"
	KafkaMessage   = "kafka_message"
	KafkaRetry     = "kafka_retry"

	RabbitmqExchangeName = "rabbitmq_exchange_name"
	RabbitmqQueueName    = "rabbitmq_queue_name"
	RabbitmqDeliveryBody = "rabbitmq_delivery_body"

	GrpcRequest = "grpc_request"
	GrpcReply   = "grpc_reply"

	ExecutorName         = "executor_name"
	ExecutorCapacity     = "executor_capacity"
	ExecutorUsage        = "executor_usage"
	ExecutorKafkaMessage = "executor_kafka_message"

	HttpClientRequestMethod         = "http_client_request_method"
	HttpClientRequestHeader         = "http_client_request_header"
	HttpClientRequestHost           = "http_client_request_host"
	HttpClientRequestPort           = "http_client_request_port"
	HttpClientRequestPath           = "http_client_request_path"
	HttpClientRequestUri            = "http_client_request_uri"
	HttpClientRequestBody           = "http_client_request_body"
	HttpClientResponseError         = "http_client_response_error"
	HttpClientResponseHeader        = "http_client_response_header"
	HttpClientResponseBody          = "http_client_response_body"
	HttpClientResponseContentLength = "http_client_response_content_length"
	HttpClientResponseStatus        = "http_client_response_status"
	HttpClientResponseStatusCode    = "http_client_response_status_code"
	HttpClientUsed                  = "http_client_used"
	HttpClientRetryCount            = "http_client_retry_count"

	ElasticIndexName       = "elastic_index_name"
	ElasticRequestBody     = "elastic_request_body"
	ElasticResponseStatus  = "elastic_response_status"
	ElasticResponseBody    = "elastic_response_body"
	ElasticBulkCount       = "elastic_bulk_count"
	ElasticBulkAddedNum    = "elastic_bulk_added_num"
	ElasticBulkIndexedNum  = "elastic_bulk_index_num"
	ElasticBulkFailedNum   = "elastic_bulk_failed_num"
	ElasticBulkMarshalFail = "elastic_bulk_marshal_fail_"
	ElasticBulkAddFail     = "elastic_bulk_add_fail_"
	ElasticBulkResult      = "elastic_bulk_result"

	WebsocketSession        = "websocket_session"
	WebsocketId             = "websocket_id"
	WebsocketCloseCode      = "websocket_close_code"
	WebsocketCloseMessage   = "websocket_close_message"
	WebsocketError          = "websocket_error"
	WebsocketEventType      = "websocket_event_type"
	WebsocketRequestUrlPath = "websocket_request_url_path"

	JobName = "job_name"
	JobFunc = "job_func"

	RedisClientName = "redis_client_name"
	RedisMethod     = "redis_method"
	RedisKey        = "redis_key"
	RedisField      = "redis_field"
	RedisValue      = "redis_value"
	RedisExpiration = "redis_expiration"
	RedisCursor     = "redis_cursor"
	RedisMatch      = "redis_match"
	RedisCount      = "redis_count"
	RedisChannel    = "redis_channel"
	RedisMessage    = "redis_message"
	SlowRedis       = "slow_redis"
)
