package contextKey

const (
	ActionId              = "action_id"
	ActionLogs            = "action_logs"
	RequestHeader         = "request_header"
	RequestHeaderLength   = "request_header_length"
	RequestTime           = "request_time"
	RequestBody           = "request_body"
	RequestBodySize       = "request_body_size"
	LogRequestBody        = "log_request_body"
	HasError              = "has_error"
	ErrorType             = "error_type"
	ErrorMessage          = "error_message"
	StackTrace            = "stack_trace"
	PlatformId            = "platform_id"
	PlatformExemption     = "platform_exemption"
	PlatformCurrencyTypes = "platform_currency_types"
	UserCache             = "user_cache"
	DeviceType            = "device_type"
	OperatorCache         = "operator_cache"
	AllowedNet            = "allowed_net"
	IpCIDR                = "ip_cidr"
	Token                 = "token"
	GetRawDataNowTime     = "get_raw_data_now_time"
	RequestBodyBufferTime = "request_body_buffer_time"
	NopCloserTime         = "nop_closer_time"
	SqlTrace              = "sql_trace"
)
